/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ManagedAccount = IDL.Record({
  'id' : IDL.Nat,
  'balance' : IDL.Float64,
  'name' : IDL.Text,
  'riskProfile' : IDL.Text,
});
export const Time = IDL.Int;
export const Trade = IDL.Record({
  'id' : IDL.Nat,
  'direction' : IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
  'profitLoss' : IDL.Float64,
  'timestamp' : Time,
  'quantity' : IDL.Float64,
  'entryPrice' : IDL.Float64,
  'exitPrice' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const PerformanceMetrics = IDL.Record({
  'roi' : IDL.Float64,
  'totalTrades' : IDL.Nat,
  'totalCapital' : IDL.Float64,
  'totalPnl' : IDL.Float64,
  'winningTrades' : IDL.Nat,
  'maxDrawdown' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAccount' : IDL.Func([ManagedAccount], [IDL.Nat], []),
  'addTrade' : IDL.Func([Trade], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAccount' : IDL.Func([IDL.Nat], [], []),
  'deleteTrade' : IDL.Func([IDL.Nat], [], []),
  'getAccount' : IDL.Func([IDL.Nat], [IDL.Opt(ManagedAccount)], ['query']),
  'getAllAccounts' : IDL.Func([], [IDL.Vec(ManagedAccount)], ['query']),
  'getAllTradesSorted' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getAllTradesSortedByPnl' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPerformanceMetrics' : IDL.Func([], [PerformanceMetrics], ['query']),
  'getTrade' : IDL.Func([IDL.Nat], [IDL.Opt(Trade)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAccount' : IDL.Func([IDL.Nat, ManagedAccount], [], []),
  'updatePerformanceMetrics' : IDL.Func([PerformanceMetrics], [], []),
  'updateTrade' : IDL.Func([IDL.Nat, Trade], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ManagedAccount = IDL.Record({
    'id' : IDL.Nat,
    'balance' : IDL.Float64,
    'name' : IDL.Text,
    'riskProfile' : IDL.Text,
  });
  const Time = IDL.Int;
  const Trade = IDL.Record({
    'id' : IDL.Nat,
    'direction' : IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
    'profitLoss' : IDL.Float64,
    'timestamp' : Time,
    'quantity' : IDL.Float64,
    'entryPrice' : IDL.Float64,
    'exitPrice' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const PerformanceMetrics = IDL.Record({
    'roi' : IDL.Float64,
    'totalTrades' : IDL.Nat,
    'totalCapital' : IDL.Float64,
    'totalPnl' : IDL.Float64,
    'winningTrades' : IDL.Nat,
    'maxDrawdown' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAccount' : IDL.Func([ManagedAccount], [IDL.Nat], []),
    'addTrade' : IDL.Func([Trade], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAccount' : IDL.Func([IDL.Nat], [], []),
    'deleteTrade' : IDL.Func([IDL.Nat], [], []),
    'getAccount' : IDL.Func([IDL.Nat], [IDL.Opt(ManagedAccount)], ['query']),
    'getAllAccounts' : IDL.Func([], [IDL.Vec(ManagedAccount)], ['query']),
    'getAllTradesSorted' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getAllTradesSortedByPnl' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPerformanceMetrics' : IDL.Func([], [PerformanceMetrics], ['query']),
    'getTrade' : IDL.Func([IDL.Nat], [IDL.Opt(Trade)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAccount' : IDL.Func([IDL.Nat, ManagedAccount], [], []),
    'updatePerformanceMetrics' : IDL.Func([PerformanceMetrics], [], []),
    'updateTrade' : IDL.Func([IDL.Nat, Trade], [], []),
  });
};

export const init = ({ IDL }) => { return []; };