/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ManagedAccount {
  'id' : bigint,
  'balance' : number,
  'name' : string,
  'riskProfile' : string,
}
export interface PerformanceMetrics {
  'roi' : number,
  'totalTrades' : bigint,
  'totalCapital' : number,
  'totalPnl' : number,
  'winningTrades' : bigint,
  'maxDrawdown' : number,
}
export type Time = bigint;
export interface Trade {
  'id' : bigint,
  'direction' : { 'buy' : null } |
    { 'sell' : null },
  'profitLoss' : number,
  'timestamp' : Time,
  'quantity' : number,
  'entryPrice' : number,
  'exitPrice' : number,
  'symbol' : string,
}
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAccount' : ActorMethod<[ManagedAccount], bigint>,
  'addTrade' : ActorMethod<[Trade], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAccount' : ActorMethod<[bigint], undefined>,
  'deleteTrade' : ActorMethod<[bigint], undefined>,
  'getAccount' : ActorMethod<[bigint], [] | [ManagedAccount]>,
  'getAllAccounts' : ActorMethod<[], Array<ManagedAccount>>,
  'getAllTradesSorted' : ActorMethod<[], Array<Trade>>,
  'getAllTradesSortedByPnl' : ActorMethod<[], Array<Trade>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPerformanceMetrics' : ActorMethod<[], PerformanceMetrics>,
  'getTrade' : ActorMethod<[bigint], [] | [Trade]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAccount' : ActorMethod<[bigint, ManagedAccount], undefined>,
  'updatePerformanceMetrics' : ActorMethod<[PerformanceMetrics], undefined>,
  'updateTrade' : ActorMethod<[bigint, Trade], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];